# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKtiC1LFwreFndCk9L_xSY_8l8698m2_
"""

!pip install google-genai sentence-transformers graphviz

import os
from google import genai
from sentence_transformers import SentenceTransformer, util
from datetime import datetime
from graphviz import Digraph
from IPython.display import Image, display, Markdown


os.environ["GEMINI_API_KEY"] = "AIzaSyDFHfcUcDKPcmpqCiYCF_ZJMbS2z0337m0"
client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
GEMINI_MODEL = "gemini-2.5-flash"


semantic_model = SentenceTransformer('all-mpnet-base-v2')


# Agent response using Gemini
def agent_response(agent_name, topic, memory, round_number):
    previous_points = ""
    for agent, args in memory.items():
        for i, arg in enumerate(args):
            previous_points += f"{agent} [Round {i+1}]: {arg}\n"

    prompt = f"""
You are {agent_name}, debating the topic: "{topic}".
Previous arguments:
{previous_points if previous_points else 'None'}

Write a concise, logical, and persuasive argument (2‑4 sentences) supporting your stance.
Consider reasoning, examples, and counterpoints to the other agent.
"""

    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=[{"text": prompt}],
    )
    text = response.text
    argument = text.replace(prompt, "").strip().split("\n")[0]
    return argument


# Memory functions
def update_memory(memory_dict, agent_name, argument):
    if agent_name not in memory_dict:
        memory_dict[agent_name] = []
    memory_dict[agent_name].append(argument)
    return memory_dict


# Judge using semantic similarity
def judge_debate(topic, memory_dict):
    summary = f"Debate Summary on: {topic}\n"
    for agent, args in memory_dict.items():
        summary += f"\n{agent} Arguments:\n"
        for i, arg in enumerate(args):
            summary += f"  [{i+1}] {arg}\n"

    topic_emb = semantic_model.encode(topic, convert_to_tensor=True)
    score = {}
    for agent, args in memory_dict.items():
        agent_score = 0
        for arg in args:
            arg_emb = semantic_model.encode(arg, convert_to_tensor=True)
            sim = util.pytorch_cos_sim(arg_emb, topic_emb).item()
            agent_score += sim
        score[agent] = agent_score / max(len(args), 1)

    winner = max(score, key=score.get)
    reason = f"Winner scored higher on semantic relevance.\nScores: {score}"
    return summary, winner, reason


# Create DAG visualization
def create_debate_dag():
    dot = Digraph(comment='Debate Simulation DAG', format='png')
    dot.node('UserInput', 'UserInputNode\n(Topic)')
    dot.node('AgentA', 'AgentA\n(Scientist)')
    dot.node('AgentB', 'AgentB\n(Philosopher)')
    dot.node('Memory', 'MemoryNode\n(Transcript)')
    dot.node('Judge', 'JudgeNode\n(Verdict)')

    dot.edges([('UserInput','AgentA'), ('UserInput','AgentB'),
               ('AgentA','Memory'), ('AgentB','Memory'),
               ('Memory','AgentA'), ('Memory','AgentB'), ('Memory','Judge')])

    return dot.render('debate_dag')


# Pretty Print Functions
def print_round(agent, round_num, argument):
    color = "blue" if agent == "Scientist" else "green"
    display(Markdown(f"### Round {round_num} - <span style='color:{color}'>{agent}</span>"))
    display(Markdown(f"> {argument}"))
    display(Markdown("---"))

def print_summary(summary, winner, reason):
    display(Markdown("## 🏁 Debate Summary"))
    display(Markdown(f"```\n{summary}\n```"))
    display(Markdown(f"### 🏆 Winner: **{winner}**"))
    display(Markdown(f"**Reason:** {reason}"))


# Run Debate
def run_debate():
    topic = input("Enter topic for debate: ")
    display(Markdown(f"# Starting debate on '{topic}' …"))
    memory = {}
    log_file = f"debate_log_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"

    agents = ["Scientist", "Philosopher"]
    with open(log_file, "w") as log:
        for round_num in range(8):
            current_agent = agents[round_num % 2]
            argument = agent_response(current_agent, topic, memory, round_num + 1)
            memory = update_memory(memory, current_agent, argument)
            print_round(current_agent, round_num+1, argument)
            log.write(f"[Round {round_num+1}] {current_agent}: {argument}\n")

        summary, winner, reason = judge_debate(topic, memory)
        print_summary(summary, winner, reason)
        log.write("\n[Judge] Summary:\n" + summary + "\n")
        log.write(f"Winner: {winner}\nReason: {reason}\n")

    dag_path = create_debate_dag()
    display(Markdown(f"### 🖼 DAG saved to: {dag_path}"))
    display(Image(dag_path))



if __name__ == "__main__":
    run_debate()

if __name__ == "__main__":
    run_debate()

if __name__ == "__main__":
    run_debate()